Move to Python 3 (#1589)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,10 @@ script: |
     echo Linting $X
     scripts/lint-recipes $X || ERR="$ERR $X"
     [[ $X == defaults-*.sh ]] && continue
-    grep -q '^#%Module' $X || { echo "ERROR: recipe $X has no modulefile"; ERR="$ERR $X"; }
+
+    # If a recipe is not a system requirement, it must have a Modulefile
+    if ! grep -qE '^system_requirement:' "$X"; then
+      grep -q '^#%Module' "$X" || { echo "ERROR: recipe $X has no modulefile"; ERR="$ERR $X"; }
+    fi
   done
   [[ ! $ERR ]] || { echo "The following recipes need to be fixed:" $ERR; exit 1; }
