Check for the presence of a Modulefile (#1099)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,5 +9,7 @@ script: |
     [[ -e $X ]] || continue
     echo Linting $X
     scripts/lint-recipes $X || ERR="$ERR $X"
+    [[ $X == defaults-*.sh ]] && continue
+    grep -q '^#%Module' $X || { echo "ERROR: recipe $X has no modulefile"; ERR="$ERR $X"; }
   done
   [[ ! $ERR ]] || { echo "The following recipes need to be fixed:" $ERR; exit 1; }
