Detect circular dependencies in recipes (#1894)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,6 +2,7 @@ dist: trusty
 language: python
 install: |
     pip install pyyaml
+    pip install alibuild
 script: |
   set -e
   ERR=
@@ -19,5 +20,6 @@ script: |
     if ! grep -qE '^system_requirement:' "$X"; then
       grep -q '^#%Module' "$X" || { echo "ERROR: recipe $X has no modulefile"; ERR="$ERR $X"; }
     fi
+    aliBuild deps --defaults o2 ${X%.sh} --outgraph deps.pdf --no-system --neat -c . || { echo "ERROR: recipe $X has circular dependency"; ERR="$ERR $X"; }
   done
   [[ ! $ERR ]] || { echo "The following recipes need to be fixed:" $ERR; exit 1; }
